apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vegetable-app
  namespace: argocd
spec:
  project: default

  source:
    # GitHub Pages URL (Helm repository)
    repoURL: https://sukhesh77.github.io/Vegetable-order-app
    chart: veg-app
    # Deploy latest released chart version
    targetRevision: "*"  # it will deploy the latest version of the chart available in the helm repository
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: sukhesh-ns 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
