apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: sukhesh-ns
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  clusterIP: None
