apiVersion: v1
kind: Service
metadata:
  name: veg-service
  namespace: sukhesh-ns
spec:
  type: LoadBalancer
  selector:
    app: veg   # Use NodePort if LoadBalancer is not supported
  ports:
    - port: 80
      targetPort: 3000
