apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.mongodb.app }}
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
