apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.statefulset.labels.app }}
  ports:
    - port: {{ .Values.statefulset.containers.port }}
      targetPort: {{ .Values.statefulset.containers.port }}
      protocol: TCP
